; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = Micro-Node-Bootloader

[env]
platform = https://github.com/BeyondRobotix/br_platformio_hwdef.git
framework = arduino
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
debug_build_flags = -O0 -g
debug_init_break = tbreak none
build_flags = -Wno-error=deprecated-declarations

; --- MicroNode (STM32L431, bxCAN) ------------------------------------------
[env:Micro-Node-Bootloader]
board = MicroNode
board_build.ldscript = ldscript.ld

[env:Micro-Node-No-Bootloader]
board = MicroNode
board_build.ldscript = ldscript-no-bootloader.ld
build_flags = ${env.build_flags} -DDISABLE_APP_SETUP

; --- CoreNode (STM32H743, FDCAN) -------------------------------------------
[env:Core-Node-Bootloader]
board = CoreNode
board_build.ldscript = ldscript.ld

[env:Core-Node-No-Bootloader]
board = CoreNode
board_build.ldscript = ldscript-no-bootloader.ld
build_flags = ${env.build_flags} -DDISABLE_APP_SETUP

; --- MicroNodePlus (STM32H723, FDCAN) --------------------------------------
[env:Micro-Node-Plus-Bootloader]
board = MicroNodePlus
board_build.ldscript = ldscript.ld

[env:Micro-Node-Plus-No-Bootloader]
board = MicroNodePlus
board_build.ldscript = ldscript-no-bootloader.ld
build_flags = ${env.build_flags} -DDISABLE_APP_SETUP
